server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movies/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Keycloak JWT Configuration (ZIP version - same as Docker)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:8080/realms/movie-booking-realm/protocol/openid-connect/certs