server:
  port: 8082

spring:
  application:
    name: movie-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:movie-db
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true